version: "3.7"
services:
  request_generator:
    image: cte:latest
    ports:
      - "55556:8086"
    networks:
      - cte
    command: /bin/bash request_generator_script.sh

  order_manager_akka:
    image: cte:latest
    ports:
      - "55557:8086"
    networks:
      - cte
    command: /bin/bash order_to_akka.sh

  order_manager_cte:
    image: cte:latest
    ports:
      - "55558:8086"
    networks:
      - cte
    command: /bin/bash order_to_cte.sh

  cte_match_engin_result_host:
    image: cte:latest
    environment:
      HOST: cte_match_engin_result_host
      ROLE: merge_result_host
      SEEDS: cte_match_engin_result_host:4445
      APP: /bin/match_engine_server
      APP_ARGS: --symbol_id_list="1,2,3,4,5,6,7,8" --is_merge_result_node

    networks:
      - cte

  #  akka gateway
  akkagateway:
    image: akka-te:latest
    environment:
      APP_CONFIG_FILE: "./gateway.conf"
    networks:
      - cte
  # akka node
  akkanode:
    image: akka-te:latest
    environment:
      APP_CONFIG_FILE: "./node.conf"
    networks:
      - cte

  trade_reciever:
    image: cte:latest
    ports:
      - "55555:8086"
    networks:
      - cte
    environment:
      CTE_MEASUREMENT_NAME: "cte_trades"
      AKKA_TE_MEASUREMENT_NAME: "akka_te_trades"
    command: /bin/bash trade_reciever_cte.sh

networks:
  cte:
    driver: bridge