version: "3.7"
services:
  request_generator:
    image: cte:latest
    networks:
      - cte
    command: /bin/bash -c "sleep 1000000000"
  order_manager_akka:
    image: cte:latest
    networks:
      - cte
    command: ./order_manager -a localhost:50051 -d localhost:8086 -m akkagateway:50051 -r akkanode:50051
  order_manager_cte:
    image: cte:latest
    networks:
      - cte
    command: ./order_manager -a localhost:50051 -d localhost:8086 -m akkagateway:50051 -r akkanode:50051
  #  akka gateway
  akkagateway:
    image: akka-te:latest
    environment:
      APP_CONFIG_FILE: "./gateway.conf"
    networks:
      - cte
  # akka node
  akkanode:
    image: akka-te:latest
    environment:
      APP_CONFIG_FILE: "./node.conf"
    networks:
      - cte
networks:
  cte:
    driver: bridge