---
- name: Run cte cluster container using latest image
  hosts: cte_match_engine
  become: true
  gather_facts: no
  tasks:
    - docker_compose:
        project_name: cte_match_engine
        state: present
        pull: yes
        recreate: always
        definition:
          version: "2.2"
          services:
            cte_match_engine:
              image: highperformancecomputing/cte:latest
              container_name: cte_match_engine
              environment:
                HOST: 172.30.28.10
                ROLE: merge_result_host
                SEEDS: 172.30.28.10:4445
                APP: /bin/match_engine_server
                APP_ARGS: --symbol_id_list="1,2,3,4,5,6,7,8" --log_file=/tmp/log/cte_match_engine.log --log_level=info
              network_mode: host
              volumes:
                - /tmp/log:/tmp/log
    - assert:
        that:
          - "cte_match_engine.cte_match_engine.state.running"