---
- name: Run cte cluster container using latest image
  hosts: cte_match_engine
  become: true
  gather_facts: no
  tasks:
    - docker_compose:
        project_name: order_manager
        state: present
        pull: yes
        recreate: always
        definition:
          version: "2.2"
          services:
            order_manager:
              image: highperformancecomputing/cte:latest
              container_name: order_manager
              environment:

              command: /bin/bash start_cte_order_manager.sh
              network_mode: host
              volumes:
                - /tmp/log:/tmp/log
    - assert:
        that:
          - "order_manager.order_manager.state.running"