name: 'Publish, deploy and run Docker image'
on: [workflow_dispatch]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: self-hosted
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: Publish Docker
        uses: elgohr/Publish-Docker-Github-Action@2.21
        with:
          name: highperformancecomputing/cte
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: latest